### PR TITLE
Linux/CMake support 

### PR DESCRIPTION
**Pull request by vitya-maleyev**
I've managed the project to be built and run on Linux: tested on Centos 7 with CMake 2.8 and Arch Linux with CMake 3.10.1.
Windows build with CMake also works and seems faster as explores parallel build feature.

### CODE REVIEW

**Comment by vitya-maleyev** [comment]
@Robinson664, could you please review?

**Comment by Robinson664** [comment]
Victor,

Sure!  I'm not familiar with git hub and my git knowledge is weak so I'm
not sure what to do.  I clicked "Merge Pull Request".  I think that did it.

-Jordan

**Comment by vitya-maleyev** [comment]
Many thanks!

**Comment by Robinson664** [comment]
Do you want to update the readme to include information about this?

**Comment by threadpool** [comment]
Hi there, I have a few questions about the evolution the API. Are you still following this thread

**Comment by Robinson664** [comment]
I get emails when I'm mentioned in the thread. I may be able to help you out if you have questions. I don't actively work on this project anymore because I don't have the time or the Bloomberg account I used to have.

**Comment by threadpool** [comment]
Hey there, 

Thanks for getting back to me.
Was the initial code based on the de complied Bloomberg source ?
I’d be happy to clone and re write  the java version and enhance it. Would  you have an issue with that. I can publish it once it’s complete.

Cheers,

Oz

**Comment by threadpool** [comment]
Can you drop me your email address please, I'll be easier to communicate. Thanks

**Comment by Robinson664** [comment]
I didn't decompile the Bloomberg source.  For the. Net version anyways, I don't think the DLL is a .Net DLL. I'm not familiar with the tools available for decompiling non-.Net DLLs. 

What you want to do with the Java version sounds cool. What did you have in mind?

My email is Robinson.JordanL+gh@Gmail.com

**Comment by threadpool** [comment]
I'm not sure if you saw my email. I’d be interested to know what your starting point for the project was. Was it the original Bloomberg source code. If so do you still have it and which language was it written in ?

**Pull request merged**
